### ISSUE TITLE
Could not open pot file

### ISSUE THREAD

**Issue by damode** [Dionach/pwdumpstats#1]
Hi, after running this python file with the suggested syntax, I am unable to get any results.
Running this command `python pwdumpstats.py pwdump.txt` gives following error message
`Could not open pot file`

When I attempt to use pot file with this syntax, `python pwdumpstats.py --pot john.pot`, I get the below output,
```
usage: pwdumpstats.py [-h] [-f FILTER_FILE] [-H] [-s] [-a] [-A] [-n] [-E] [-c]
                      [-d] [-D] [-p POT_FILE] [-m] [-l]
                      files [files ...]
pwdumpstats.py: error: too few arguments
```
Please advise. Thanks

**Comment by rbsec** [comment]
You need to specify both the pot (which has the cracked hashes), and the pwdump file that you want to analyse:

```
python pwdumpstats.py --pot john.pot pwdump.txt
```

**Comment by damode** [comment]
That worked perfectly. Thanks!
